### ISSUE TITLE
Better way to serialize state for saved games

### ISSUE THREAD

**Issue by KevinElberger** [KevinElberger/RoguePG#11]
The biggest sources of state are:

- The Hero
- The Inventory
- The GUI
- The Dungeon

If we can perhaps create a function on each of these classes called `serialize()`, maybe we can call that and pass it all into the state object.

**Comment by KevinElberger** [comment]
@StevenElberger - I am thinking we can create a `Serializer` class that can take in object instances and encode/decode them. It can have an `encode` and `decode` method. Thoughts on this approach?

**Comment by StevenElberger** [comment]
After some research on serializing game state (didn't yield many helpful results), it seems like the usual approach is a class responsible for keeping track of all the state to serialize. This class then serializes all of the state to a file and can read it back in to deserialize it. This seems to be what we're already doing. I think in an effort to trim the code down a bit we can introduce a method onto specific classes which contain a lot of state that is manually extracted. This method would simply return the state necessary to serialize that class. E.g., for the Hero class we can just add `getSaveState` or `serialize` (whichever works for me) and in the StateManager class we'd simply call `this.scene.hero.serialize()`.

I think we'd have a difficult time trying to improve how we serialize the game. The `save()` method is only a few lines long and it completely serializes the game. It doesn't get much simpler than that. I wasn't aware we needed to serialize the GUI - what does that involve? Also, I thought we already serialized the inventory, but if that needs to be serialized I think we can do so fairly easily.

**Comment by KevinElberger** [comment]
Thanks for doing some research on it (I know the search results are sparse). This is the conclusion that I came to when stumbling upon [this thread](http://www.html5gamedevs.com/topic/13631-saving-game-data/). Feudalwars made a very successful game via Phaser 2, so whenever he posts it is always worth reading over. I know that thread was old but it seems like nothing has really changed.

I think at the time of my writing the initial comment, the GUI might have functioned a bit differently. We will not need to serialize it since all its values depend upon those of the Hero (experience, health, gold, attack, defense).

Inventory already has a de-serialize method inside the `StateManager`. I believe that is all it will need, so nothing specific needs to be done with the actual inventory as long as we have all the items that were in the level at the time of saving.

**Comment by KevinElberger** [comment]
Added in commit [a836321](https://github.com/KevinElberger/RoguePG/commit/a83632105176d3e2ad4c14b1b7a9e319dc33a6a9).
