### ISSUE TITLE
Improve Enemy Following AI

### ISSUE THREAD

**Issue by StevenElberger** [KevinElberger/RoguePG#20]
Enemies won't prioritize attacking the hero over following the hero. For example, find a rat and stay horizontal with it 2 squares away so that there is a square in between the hero and the rat. Now move north/south on the map and watch as the rat moves at the same time the hero does. Shouldn't the rat be moving toward the hero instead of parallel so that it can attack?

Even still, if the hero is right next to the rat in the above scenario and the hero moves north/south the rat still won't attack and will simply move together with the hero.

**Comment by KevinElberger** [comment]
One patch I am going to add is that the Rats seem to stop if they are in front of the skeleton floor tile.

**Comment by StevenElberger** [comment]
The AI is better for sure but yes I did notice the skeleton floor tile issue and also the same issue with the rats remaining parallel seems to still exist.

**Comment by KevinElberger** [comment]
Improved in commit [c1d9861](https://github.com/KevinElberger/RoguePG/commit/c1d9861a79e9114fb447c88d5215b939236cc62f). Will re-visit when this project is in the polishing state.
